# Generated by Django 3.2.18 on 2023-04-24 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_recipie'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Recipie',
            new_name='Receipe',
        ),
    ]
