# Generated by Django 3.2.18 on 2023-04-24 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_recipie_receipe'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Receipe',
            new_name='Recepie',
        ),
    ]
